site_name: LeetCodebySmile
site_url: https://smilingwayne.github.io/LeetCode/
site_description: 笑笑的题库!

nav:
  - 首页: index.md
  - 日常:
      - Daily/index.md
      - 数组: Daily/Array.md
  - 第二部分:
      - Part2/index.md
  - 面试题:
      - 回溯: Interview/Interview1.md
  - 100题&面试150题:
      - 综合与记不得的: Hot100/Appendix.md
      - 二叉树: Hot100/Bin_Tree.md
      - 双指针｜滑动窗口: Hot100/Two_Pointer_sliding_window.md
      - 动态规划: Hot100/DP.md
      - 链表: Hot100/LinkedList.md
      - 回溯: Hot100/Backtrack.md
      - 列表｜矩阵: Hot100/Array.md
      - 栈｜队列: Hot100/Stack.md
      - 二分搜索: Hot100/Bin_search.md
      - DFS/BFS: Hot100/DFS_BFS.md
      - 贪心算法: Hot100/Greedy.md
      - 哈希: Hot100/Hash.md

docs_dir: docs/

theme:
  name: material
  custom_dir: docs/theme/overrides/
  palette:
    primary: teal
  features:
    - navigation.tabs
    - search.suggest
    - search.highlight
    - search.share
    - navigation.top
    - navigation.indexes
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/
    - icon: fontawesome/solid/paper-plane
      link: mailto:xiaoxiaowayne@163.com

plugins:
  - statistics
  - tags:
      tags_file: index.md
  - git-authors:
      show_contribution: true
      exclude:
        - index.md
      enabled: true
  - git-revision-date-localized:
      type: datetime
      custom_format: "%d %B %Y"
      timezone: Asia/Shanghai
      locale: en
      fallback_to_build_date: false
      enable_creation_date: true
      exclude:
        - index.md
      enabled: true
  - rss:
      date_from_meta:
        as_creation: "date" # means from page.meta.date
        as_update: "date" # means from git log
        datetime_format: "%Y-%m-%d %H:%M"
        default_time: "09:30"
        default_timezone: Asia/Shanghai
      enabled: true
      feed_description: "My custom feed description" # MkDocs site_description: will be used if this key is not present
      feeds_filenames:
        json_created: feed_json_created.json
        json_updated: feed_json_updated.json
        rss_created: feed_rss_created.xml
        rss_updated: feed_rss_updated.xml

markdown_extensions:
  - admonition
  - def_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.mark
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator:
        !!python/name:material.extensions.emoji.to_svg # Update 2023.12.18 for locations


extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - https://vercount.one/js

extra_css:
  - stylesheets/extra.css
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css

copyright: Copyright &copy; 2022 - 2025 xiaoxiaoWayne
