name: update
on:
  push:
    branches:
      - main
permissions:
  contents: write
env:
  TZ: Asia/Shanghai
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material mkdocs-git-revision-date-localized-plugin mkdocs-rss-plugin mkdocs-git-authors-plugin mkdocs-mermaid2-plugin
      - name: Install modified mkdocs-statistics-plugin
        run: |
          git clone https://github.com/KinnariyaMamaTanha/mkdocs-statistics-plugin
          pip install ./mkdocs-statistics-plugin
          rm -rf mkdocs-statistics-plugin
      - run: pip cache purge
      - run: mkdocs gh-deploy --force
